project:
  type: website
  output-dir: _site

website:
  title: "BuffaloBadger"
  navbar:
    title: false
    search: true
    logo: graphics/Banner.png
    left:
      - text: "Reaction Engineering Basics"
        href: http://buffalobadger.github.io/RE_Basics
      - text: "SCoRE"
        href: file:///Users/lund/Projects/Kinetics/SCoRE/_site/index.html
      - text: "ToTaL Engineering"
        href: file:///Users/lund/Projects/ToTaL_Engineering/_site/index.html
      - text: "The Sett"
        href: file:///Users/lund/Projects/The_Sett/_site/index.html
      - text: "About"
        href: about.qmd
  search:
    location: navbar
    type: overlay
  page-footer:
    background: light
    right: 
      - text: Copyright 2023, Carl Lund 
  favicon: graphics/BuffaloBadger_16_16.png

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
