project:
  type: website
  output-dir: _site

website:
  title: "BuffaloBadger"
  navbar:
    title: false
    search: true
    logo: Banner.png
    left:
      - text: "ToTaL PS"
        href: total_ps.qmd
      - text: "Reaction Engineering Basics"
        href: http://buffalobadger.github.io/RE_Basics
#      - text: "SCoRE"
#        href: score.qmd
#      - text: "The Sett"
#        href: sett.qmd
      - text: "About"
        href: about.qmd
  search:
    location: navbar
    type: overlay

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



