project:
  type: website
  output-dir: _site

website:
  title: "BuffaloBadger"
  navbar:
    title: false
    search: true
    logo: graphics/Banner.png
    left:
      - text: "REB, The Book"
        href: http://buffalobadger.github.io/RE_Basics
      - text: "REB, The Course"
        href: http://buffalobadger.github.io/RE_Basics_Course
      - text: "REB, The Design"
        href: http://buffalobadger.github.io/RE_Basics_Design
      - text: "The Sett"
        href: http://buffalobadger.github.io/The_Sett
      - text: "About"
        href: about.qmd
  search:
    location: navbar
    type: overlay
  page-footer:
    background: light
    right: 
      - text: Copyright 2026, Carl Lund 
  favicon: graphics/BuffaloBadger_16_16.png

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
